AWSTemplateFormatVersion: '2010-09-09'
Description: Capa de Computo y Auto Scaling - Parcial 1029215-maicol

Parameters:
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  EC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: lt-parcial-1029215-maicol
      LaunchTemplateData:
        ImageId: ami-0cca150d127c2216f # Amazon Linux en us-east-1
        InstanceType: t2.micro # 100% Capa Gratuita
        SecurityGroupIds:
          - !ImportValue EC2SG-1029215-maicol
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            echo "<h1>Resolucion Parcial - $(hostname -f)</h1>" > /var/www/html/index.html

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: asg-parcial-1029215-maicol
      VPCZoneIdentifier: !Ref Subnets
      LaunchTemplate:
        LaunchTemplateId: !Ref EC2LaunchTemplate
        Version: !GetAtt EC2LaunchTemplate.LatestVersionNumber
      MinSize: '2'
      MaxSize: '6'
      DesiredCapacity: '2'
      TargetGroupARNs:
        - !ImportValue TG-1029215-maicol
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      Tags:
        - Key: Name
          Value: ec2-asg-1029215-maicol
          PropagateAtLaunch: true

  ASGWarmPool:
    Type: AWS::AutoScaling::WarmPool
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      MinSize: 1
      PoolState: Stopped

  # =========================================================================
  # ESCALABILIDAD PROGRAMADA (Ejecución única basada en minutos en tiempo real)
  # =========================================================================
  
  # Accion 1: Escalar a 4 instancias
  # Se ejecutara a las 11:00 PM hora Colombia (04:00 AM UTC)
  ScaleOutAction1:
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      DesiredCapacity: 4
      StartTime: "2026-06-06T04:00:00Z" 

  # Accion 2: Escalar a 5 instancias
  # Se ejecutara a las 11:10 PM hora Colombia (04:10 AM UTC)
  ScaleOutAction2:
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      DesiredCapacity: 5
      StartTime: "2026-06-06T04:10:00Z"

  # Accion 3: Reducir a 3 instancias
  # Se ejecutara a las 11:20 PM hora Colombia (04:20 AM UTC)
  ScaleInAction1:
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      DesiredCapacity: 3
      StartTime: "2026-06-06T04:20:00Z"

  # Accion 4: Reducir a la capacidad base de 2 instancias
  # Se ejecutara a las 11:30 PM hora Colombia (04:30 AM UTC)
  ScaleInAction2:
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      DesiredCapacity: 2
      StartTime: "2026-06-06T04:30:00Z"